/* START DROPS */

DROP DOMAIN IF EXISTS NETEXT;
DROP DOMAIN IF EXISTS PASSWORD;
DROP DOMAIN IF EXISTS EMAIL;
DROP DOMAIN IF EXISTS ZIPCODE;

/* END DROPS */

/* START CREATES */

CREATE DOMAIN NETEXT AS TEXT
CONSTRAINT not_empty CHECK (LENGTH(VALUE) > 0);

CREATE DOMAIN PASSWORD AS TEXT
CONSTRAINT valid_password CHECK (VALUE ~ '^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()])[A-Za-z\d!@#$%^&*()]{8,}$');

CREATE DOMAIN EMAIL AS TEXT
CONSTRAINT valid_email CHECK (VALUE ~ '^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$');

CREATE DOMAIN ZIPCODE AS TEXT
CONSTRAINT valid_zip CHECK (VALUE ~ '^\d{5}$');

/* END CREATES */
